coverage:
  precision: 2
  round: down
  range: "60...100"

  status:
    project:
      default:
        target: 60
        informational: true
    patch:
      default:
        target: 60
        informational: true